manifest_version = "0.1.0"
name = "compute-rust-auth"
description = "Authentication at the edge with OAuth 2.0, PKCE, and OpenID Connect"
authors = ["Dora Militaru <dmilitaru@fastly.com>"]
language = "rust"
service_id = "2OhGXZD9s3EzEYh2h1I2ef"
version = 305
