version = 13
name = "compute-rust-auth-experiment"
description = "Authentication at the edge with OAuth 2.0, PKCE, and OpenID Connect"
authors = ["Dora Militaru <dmilitaru@fastly.com>"]
language = "rust"
service_id = "1q8BCEpqp1F0atRXzoHyJo"
