# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["<oss@fastly.com>"]
description = "Connect to an identity provider such as Auth0 using OAuth 2.0 and validate authentication status at the Edge, to authorize access to your edge or origin hosted applications."
language = "rust"
manifest_version = 2
name = "Authenticate at edge with OAuth"

[local_server]

  [local_server.backends]

    [local_server.backends.backend]
      url = "https://httpbin.org"

    [local_server.backends.idp]
      url = "https://accounts.google.com"

[setup]

  [setup.backends]

    [setup.backends.backend]
      address = "httpbin.org"
      description = "Content or application origin"

    [setup.backends.idp]
      address = "accounts.google.com"
      description = "Identity provider authorization server"
