authors = ["<oss@fastly.com>"]
name = "Authenticate at edge with OAuth"
description = "Connect to an identity provider such as Google using OAuth 2.0 and validate authentication status at the Edge, to authorize access to your edge or origin hosted applications."
language = "rust"
manifest_version = 2

[setup]

  [setup.backends]

    [setup.backends.backend]
      description = "Content or application origin"
      address = "httpbin.org"

    [setup.backends.idp]
      description = "Identity provider authorization server"
      address = "accounts.google.com"

[local_server]
  [local_server.backends]
    [local_server.backends.idp]
      url = "https://accounts.google.com/"
    [local_server.backends.backend]
      url = "https://httpbin.org/"